### ISSUE TITLE
small fix to the Jointly repo - add documentation link to landing page https://github.com/hpi-dhc/jointly 

### ISSUE THREAD

**Issue by lwasser** [hpi-dhc/jointly#13]
Hi there 👋 jointly maintainers! i have a small request.
Jointly is the only pyOpenSci package that is missing a link to their docs - https://github.com/hpi-dhc/jointly on the landing page of the repo. 

## Note below there is no link to the docs in the about section

<img width="435" alt="Screen Shot 2023-08-15 at 7 01 12 PM" src="https://github.com/hpi-dhc/jointly/assets/7649194/6c0b3eaf-6278-49ea-acb6-7eb267616a5f">

 it's a small fix to add it on the repo landing page. could you kindly add that? 

<img width="514" alt="Screen Shot 2023-08-15 at 7 00 21 PM" src="https://github.com/hpi-dhc/jointly/assets/7649194/dbbd4d58-7e31-4ef9-b63d-1bac225cdccf">

we are parsing this information for all packages in our ecosystem and this is the only package that it can't parse correctly!

Note that the same issue arises with devicely. should i open an issue there as well or is this one sufficient for both?

Many thanks for your help here!

**Comment by enra64** [comment]
Hi, did it for jointly. For devicely I don't have the rights, please ask @arianesasso  or @jostmorgenstern

**Comment by arianesasso** [comment]
Thank you @enra64 :). I will fix it for devicely!

**Comment by arianesasso** [comment]
@lwasser done 😉

**Comment by lwasser** [comment]
thank you BOTH!!! so helpful. 🚀
